# Generated by Django 4.0.3 on 2022-04-06 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('economy_sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='Indicates whether or not the standard is public or for internal use')),
            ],
        ),
        migrations.AlterField(
            model_name='economysectorrelation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='economysector',
            name='standard',
            field=models.ForeignKey(help_text='The standard this code is defined by.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='economy_sectors', to='economy_sectors.standard'),
        ),
        migrations.AlterField(
            model_name='economysectorrelation',
            name='to_standard',
            field=models.ForeignKey(help_text='The standard to which the conversion is happening.', on_delete=django.db.models.deletion.CASCADE, related_name='economy_sectors_relations', to='economy_sectors.standard'),
        ),
    ]
